name: CI
on:
  push:
jobs:
  release:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: biblioteksentralen/github-actions/node-setup@main
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
