name: CI
on:
  release:
    types: [created]
jobs:
  publish-gpr:
    name: Publish to NPM
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: biblioteksentralen/github-actions/node-setup@main
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
